# Use postgres/example user/password credentials
version: '3.1'

services:

  beershopdb:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/data:/tmp/data
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
